name: Android Build

on: push

jobs:
  build:

    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Demo App
        run: ./gradlew assemble
        