name: Android Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Android Build from MarketPlace
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"
